# Full reference https://github.com/foundry-rs/foundry/tree/master/config

[profile.default]
  auto_detect_solc = true
  bytecode_hash = "none"
  cbor_metadata = false
  evm_version = "cancun"
  fuzz = { runs = 1_000 }
  gas_reports = ["*"]
  libs = ["lib"]
  optimizer = true
  optimizer_runs = 1000
  out = "out"
  script = "script"
  src = "src"
  test = "test"
  fs_permissions = [{ access = "read-write", path = "./" }, { access = "read", path = "../avs/contracts/deployments/bond-yield" }]

[fmt]
  bracket_spacing = true
  int_types = "long"
  line_length = 118
  multiline_func_header = "all"
  number_underscore = "thousands"
  quote_style = "double"
  tab_width = 4
  wrap_comments = true